name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup JDK 17 for the build
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      # Step 4: Extract PR number and set the dynamic project version
      - name: Set PR Version
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      # Step 5: Run the Maven tests
      - name: Test with Maven
        run: mvn test -Drevision=0.0.${{ env.PR_NUMBER }}-SNAPSHOT

      # Step 6: Build the Maven package with dynamic version
      - name: Build with Maven
        run: mvn package -Drevision=0.0.${{ env.PR_NUMBER }}-SNAPSHOT

      - name: Build Docker Image
        run: |
          docker build --build-arg PR_NUMBER=${{ env.PR_NUMBER }} -t my-app:0.0.${{ env.PR_NUMBER }}-SNAPSHOT .
